version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install -E docs

mkdocs:
  configuration: mkdocs.yml
